### ISSUE TITLE
Freeze when opening/closing window

### ISSUE THREAD

**Issue by stumpuser** [stumpwm/stumpwm#630] opened 2019-07-27 07:08 UTC
Sometimes when you open or close window StumpWM freezes. It's reproducible if you open ~10 terminals and then close them, not reliable but if you repeat this process for ~1min you'll probably encounter it. Another thing I noticed is that even if neither mouse pointer nor keyboard responding visually it'll still close/open window if you press corresponding hotkeys during the freeze. I noticed this behavior recently but I haven't updated stumpwm source for couple of months(I updated it now) but I update sbcl regularly so it might be connected to something external to stumwpm. Not sure how to debug it.

**Comment by alexanderbarbosa** [comment] 2019-07-27 18:37
Did you try with different terminal emulators? Its wise to open just Stumpwm and that terminal and try to reproduce, with minimal or no background process as dunst and alikes...

It would help if you share some info on your system and how you built stumpwm.

What OS/distro, sbcl version, which terminal...

You can always redirect errors to a file.

More:
As for debugging: https://github.com/stumpwm/stumpwm/wiki/Freezes

**Comment by stumpuser2** [comment] 2019-08-09 05:45
@alexanderbarbosa I figured it out, it was due to buggy intel driver, I changed acceleration method from uxa to sna and I haven't had any freezes so far.
We can close the issue, I lost access to my original account so I can't do it myself.

**Closed** 2019-08-09 08:28 UTC
