### ISSUE TITLE
Change location of dump files

### ISSUE THREAD

**Issue by equwal** [stumpwm/stumpwm#746] opened 2020-03-09 01:58 UTC
The `dump` commands which use `dump-to-file` default to dirtying the home directory. I suggest having a default/configurable dot directory that they go into, and adding some kind of default extension. Something like this:

```
/home/user/.stumpdumps/
    |-  vsplit.dump
    |-  scratchgroup.dump
```
While commands still working the same:
```
: dump-desktop-to-file
Dump To File: vsplit
```
Also the restore commands should be expected to work the same as before.

**Comment by PuercoPop** [comment] 2020-03-09 02:41
imho If we are to add an new directory we should follow the [XDG Base directory standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and use  `$XDG_DATA_HOME` which would default to  `~/.local/share/stumpwm/`

**Comment by equwal** [comment] 2020-03-09 03:23
> imho If we are to add an new directory we should follow the [XDG Base directory standard](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) and use `$XDG_DATA_HOME` which would default to `~/.local/share/stumpwm/`

I agree that this is a good default choice.

**Comment by equwal** [comment] 2020-03-15 02:36
Merging the pull will close the issue.

**Comment by sjl** [comment] 2020-09-23 16:28
Today I wanted to hack on StumpWM, and figured I should update it before I did so so my changes would merge cleanly, but hesitated because every time I update StumpWM something invariably breaks and I have to spend 10-20 minutes debugging my window manager instead of doing actual work.  I figured I'd take that chance and roll the dice, and sure enough, something *immediately* broke, and this change was the culprit.  My mappings to load my various screen layouts from my dotfiles repository suddenly no longer work:

```
(define-top-keys ;; layout
  ("s-H-m" "restore-from-file /home/sjl/src/dotfiles/stumpwm/dev.lisp")
  ("s-H-s" "restore-from-file /home/sjl/src/dotfiles/stumpwm/streaming.lisp")
  ("s-H-w" "restore-from-file /home/sjl/src/dotfiles/stumpwm/work.lisp")
  ("s-H-z" "restore-from-file /home/sjl/src/dotfiles/stumpwm/zoom.lisp"))
```

I understand that this change feels cleaner, but *please* consider backwards compatibility when "fixing" things like this.  If someone updates to the latest version of StumpWM and things that are working suddenly break, that's not an upgrade, that's a downgrade.  I guess in this case I'll just sigh and set up Yet Another Symlink To My Dotfiles Repo but not everyone has the same tolerance for their window manager breaking all the time and might get chased away.

Or at *least* have some kind of changelog where backwards-incompatible changes like this get listed so I don't have to go grovelling through the StumpWM source to find out what's going to break every time I update StumpWM.

**Comment by equwal** [comment] 2020-09-24 23:42
> Today I wanted to hack on StumpWM, and figured I should update it before I did so so my changes would merge cleanly, but hesitated because every time I update StumpWM something invariably breaks and I have to spend 10-20 minutes debugging my window manager instead of doing actual work. I figured I'd take that chance and roll the dice, and sure enough, something _immediately_ broke, and this change was the culprit. My mappings to load my various screen layouts from my dotfiles repository suddenly no longer work:
> 
> ```
> (define-top-keys ;; layout
>   ("s-H-m" "restore-from-file /home/sjl/src/dotfiles/stumpwm/dev.lisp")
>   ("s-H-s" "restore-from-file /home/sjl/src/dotfiles/stumpwm/streaming.lisp")
>   ("s-H-w" "restore-from-file /home/sjl/src/dotfiles/stumpwm/work.lisp")
>   ("s-H-z" "restore-from-file /home/sjl/src/dotfiles/stumpwm/zoom.lisp"))
> ```
> 
> I understand that this change feels cleaner, but _please_ consider backwards compatibility when "fixing" things like this. If someone updates to the latest version of StumpWM and things that are working suddenly break, that's not an upgrade, that's a downgrade. I guess in this case I'll just sigh and set up Yet Another Symlink To My Dotfiles Repo but not everyone has the same tolerance for their window manager breaking all the time and might get chased away.

I'm sorry that I wasn't able to forsee that this breaks absolute paths. That is definitely a bug.

> Or at _least_ have some kind of changelog where backwards-incompatible changes like this get listed so I don't have to go grovelling through the StumpWM source to find out what's going to break every time I update StumpWM.

I like that StumpWM is an experimental WM and not just an obscure stable one. I think it would benefit from **tagging releases** or having a dev branch. Because I don't like it either when my pull request turns out to inconvenience people in unforseen ways, and then I have to scramble to fix something I broke on master.

**Comment by dmb2** [comment] 2020-09-25 01:01
StumpWM is supposed to be a stable piece of software and the API is fairly static.  We do our best to avoid breaking backward compatability.  In this case, we had a regression that happened when we tried to be more compatible with desktop standards.  While this is definitely a bug, it was introduced in good faith and is one of the consequences of living on master.  In this case, this bug would have been introduced in a stable tagged release, so while you have the feature freeze if you only go by our releases, you also miss bugfixes and new features that come along with master.

I'm sorry your experience was so frustrating, I've been in the same position and felt the same pay, unfortunately there's no way to foresee bugs like this.

@equwal Please feel free to explain that your PRs are untested or lightly tested, and also feel free to request code reviews before requesting they be merged so that we can check them or test them a bit more than normal.

**Comment by landakram** [comment] 2021-02-08 04:38
Hey folks,  I too ran into the breaking change inadvertently introduced by the above PR when I upgraded stumpwm. In my case, winner-mode stopped working (this issue has already been referenced above).

I put up a PR (https://github.com/stumpwm/stumpwm/pull/852) that retains the ability to specify an absolute path, but defaults to XDG_DATA_HOME/stumpwm/<file>.dump for everything else. Beyond what @sjl said above, I think winner-mode is a pretty good example for why we might want this: winner-mode makes a lot of dumps that shouldn't necessarily be kept around, and I much prefer putting those in /tmp rather than XDG_DATA_HOME.

**Closed** 2021-02-09 01:53 UTC
