### ISSUE TITLE
Stumpwm freezes when Xcrysden loses focus to an empty group.

### ISSUE THREAD

**Issue by aoterodelaroza** [stumpwm/stumpwm#226] opened 2015-09-25 05:19 UTC
Hi  all,
The xcrysden program (version 1.5.60, from the debian/testing repo) freezes stumpwm when these steps are followed:
1. Open a terminal in an empty tiled group.
2. Call xcrysden from it. xcrysden needs to have focus to reproduce this issue.
3. gnext to a different tiled group. This other group needs to be empty, otherwise stumpwm doesn't freeze.
I'm using the master branch of the stumpwm git repo on debian/testing, compiled with sbcl (version 1.2.15.debian). Until now, it's the only program I've found that shows this behavior, so it may be a problem with xcrysden, not stumpwm. 
I used debug-level 10, but couldn't see anything funny. Basically, stumpwm keeps going (spamming timeout and :NO-EXPOSURE messages), but key presses or mouse clicks do not register anymore.

**Comment by dbjergaard** [comment] 2015-09-29 09:11
I'll check this out.  It looks like a pretty old program (in fact 1.5.60 is the same version in jessie/stable).  Offhand I'm not sure what could be causing it though.

**Comment by dbjergaard** [comment] 2015-11-17 15:42
could you paste the log somewhere and link to it? It might help me figure out whats going on if I can't get the bug to be reproduced

**Comment by aoterodelaroza** [comment] 2015-11-18 18:53
Sure. You can find the stumpwm output here:
{% gist ff5c70d4c69989a33db0 %}
I opened stumpwm, then a gnome-terminal, xcrysden, and switched to an empty group, at which point stumpwm froze.

**Comment by dbjergaard** [comment] 2015-11-19 13:19
did you mean to close this?

**Comment by aoterodelaroza** [comment] 2015-11-19 17:23
Ooops, no, sorry. Misclick.

**Comment by dbjergaard** [comment] 2015-11-19 17:29
thanks for the log I'll look into this.

**Comment by dbjergaard** [comment] 2016-01-21 16:02
Confirmed.  I've seen this in other programs, but your procedure for reproducing this works! Thanks! I'll dig further into debugging this soon.

**Comment by dbjergaard** [comment] 2016-01-21 16:03
In the mean time, clicking (with the mouse) will make stumpwm listen to events again so you can keep running without restarting.

**Comment by aoterodelaroza** [comment] 2016-01-21 16:24
Thanks! That works for me.

**Comment by dmb2** [comment] 2019-11-27 23:08
Fixed!

**Closed by dmb2** 2019-11-27 23:08 UTC
Labels: bug

**Comment by aoterodelaroza** [comment] 2019-11-28 07:16
Thanks! :)
