### ISSUE TITLE
opening/pulling window into empty frame, prior window keeps focus-border

### ISSUE THREAD

**Issue by okflo** [stumpwm/stumpwm#340] opened 2017-03-23 11:45 UTC
If you open a new window or pull a window in an empty frame and there
is another prior window in another frame - that had focus - the prior
window decoration is not updated respectively the "focus-border"
stays resulting in two windows having the "focus-border".

Steps to reproduce:

- start with an empty group
- open f.e. terminal 
- split frame
- fselect (empty) frame
- open f.e another terminal

result: both terminal-windows have a "focus-border"

tested with current stumpwm from quicklisp and current stumpwm from
github with empty stumpwmrc.

sbcl --version
SBCL 1.3.15
uname -a
Linux lobsang 4.10.4-1-ARCH #1 SMP PREEMPT Sat Mar 18 19:39:18 CET 2017 x86_64 GNU/Linux

as a quick (ugly) fix I call update-decoration on all windows whenever a new window is created:

```
(defun redecorate-all-windows (w)
  (declare (ignore w))
  (loop for i being the elements of (group-windows (current-group))
     do (update-decoration i)))

(add-hook *new-window-hook*
          #'redecorate-all-windows)
```
best regards
  okflo

**Comment by jorams** [comment] 2017-03-26 11:24
This was caused by 82859b20ab5456d1961b0b971e5f4b78bfc2378c. The `no-focus` function (that gets called when focusing the empty frame) wouldn't update the group's `current-window` slot, causing the `update-decoration` call for the no-longer-focused window to think it was still in focus.

Fixed by 3634c9a4ca17d60c4f8c96170b5b72f802912833.

**Closed by jorams** 2017-03-26 11:24 UTC
