### ISSUE TITLE
Non-ascii keybindings

### ISSUE THREAD

**Issue by zarkone** [stumpwm/stumpwm#194] opened 2015-03-02 07:29 UTC
Hello! 

When I switch layout to RU, i can't use the shortcuts:
`Menu Cyrillic_el not bound`
I don't want to remap all standard and custom shortcuts, maybe there's simple solution? Thank you!
(Sorry if i this is wrong place for such issues..)

**Comment by dbjergaard** [comment] 2015-03-02 12:47
Duplicate of #111

**Comment by dbjergaard** [comment] 2015-03-09 17:01
Maybe this isn't a duplicate, can you be a little more clear about how you got the error you posted? If you set your layout to RU, and press any key you get an error like that?  

I think even if we get cyrillic keys supported (they aren't now), someone will still have to write a .stumpwmrc that rebinds the keys.

**Comment by zarkone** [comment] 2015-03-10 03:30
> If you set your layout to RU, and press any key you get an error like that? 
Yes. And you're rigth, it's not the same, but i have #111 too.

> someone will still have to write a .stumpwmrc that rebinds the keys.
First i've tried to google it before posting issue, but i couldn't =(

I'm using ```Debian 7```, but i also have ```Ubuntu 14.04``` machine with stumpwm
from repos. I've tried to change layout and use shortcut and it worked,
with no cyrillic rebindings... Also i've tried to use cyrillic in ```C-t
!``` shell command window and get english characters instead of
cyrillic. So, it looks like wm doesn't know about layout changings in
this version.


David Bjergaard writes:

> Maybe this isn't a duplicate, can you be a little more clear about how you got the error you posted? If you set your layout to RU, and press any key you get an error like that?  
>
> I think even if we get cyrillic keys supported (they aren't now), someone will still have to write a .stumpwmrc that rebinds the keys.  
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/stumpwm/stumpwm/issues/194#issuecomment-77895764

-- 
Sent with my mu4e

**Comment by dbjergaard** [comment] 2015-03-10 11:56
That sounds correct.  StumpWM only handles ascii input on a US 105 key
keyboard.  I'm working to support utf8 keys for the input boxes, but I
don't know if we'll ever be able to fully support a cyrillic keyboard
layout the way your describing.

    Dave

**Comment by zarkone** [comment] 2015-03-10 15:19
Is it possible to use key codes instead of symbols  somehow? 
```bash
$ xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'
41 f
41 Cyrillic_a
```

p.s. Github email reply doesn't support Markdown, so sad...

**Comment by dbjergaard** [comment] 2015-03-10 15:32
So, the files in stumpwm that you want to look at are keytrans.lisp and
keysyms.lisp.  There are a few things going on here:
1. StumpWM can't render unicode strings, so it won't display the right
   characters in the mode-line or in input boxes
2. StumpWM (afaik) can't take a unicode string from and input box and
   "do the right thing" even if it can't render the string
3. Assuming you can work around 1 and 2, I don't completely understand
   how the key symbols get translated into stumpwm commands when they
   aren't the standard keys.  You'll want to dig into kmap.lisp and work
   your way out from kbd on line 146

I wish github emails supported Markdown too

    Dave

**Comment by a13** [comment] 2015-03-10 15:41
try this workaround:
xkbcomp $DISPLAY - | egrep -v "group . = AltGr;" | xkbcomp - $DISPLAY

**Comment by zarkone** [comment] 2015-03-10 15:48
It works, thank you very much! 
D.D. writes:

> try this workaround:
> xkbcomp $DISPLAY - | egrep -v "group . = AltGr;" | xkbcomp - $DISPLAY
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/stumpwm/stumpwm/issues/194#issuecomment-78080767

-- 
Sent with my mu4e

**Comment by zarkone** [comment] 2015-03-10 15:53
Thanks David! I'll try to understand what's going on in this files if my
common lisp skills allow me to.

David Bjergaard writes:

> So, the files in stumpwm that you want to look at are keytrans.lisp and
> keysyms.lisp.  There are a few things going on here:
> 1. StumpWM can't render unicode strings, so it won't display the right
>    characters in the mode-line or in input boxes
> 2. StumpWM (afaik) can't take a unicode string from and input box and
>    "do the right thing" even if it can't render the string
> 3. Assuming you can work around 1 and 2, I don't completely understand
>    how the key symbols get translated into stumpwm commands when they
>    aren't the standard keys.  You'll want to dig into kmap.lisp and work
>    your way out from kbd on line 146
>
> I wish github emails supported Markdown too
>
>     Dave
>
> Anatoly Smolyaninov <notifications@github.com> writes:
>
>> Is it possible to use key codes instead of symbols somehow? 
>>
>> $ xev | grep -A2 --line-buffered '^KeyRelease' | sed -n '/keycode /s/^.*keycode \([0-9]*\).* (.*, \(.*\)).*$/\1 \2/p'
>> 41 f
>> 41 Cyrillic_a
>>
>> p.s. Github email reply doesn't support Markdown, so sad... 
>>
>> —
>> Reply to this email directly or view it on GitHub.
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/stumpwm/stumpwm/issues/194#issuecomment-78078815

-- 
Sent with my mu4e

**Comment by dbjergaard** [comment] 2016-01-28 18:43
@a13 can you explain how your workaround works, and if it can be adapted for other issues with non-ascii keybindings?

**Comment by a13** [comment] 2016-01-28 21:59
I think you can get some useful information  from [here](https://bugs.freedesktop.org/show_bug.cgi?id=506)

**Comment by a13** [comment] 2016-01-28 22:02
comment 6

**Comment by dbjergaard** [comment] 2016-11-14 15:37
I'm going to close this for now, we can revisit this when we have proper support for non-english keyboard events in clx upstream.

**Closed by dbjergaard** 2016-11-14 15:37 UTC
Labels: duplicate

**Comment by marasenna** [comment] 2023-09-10 13:56
> try this workaround: xkbcomp $DISPLAY - | egrep -v "group . = AltGr;" | xkbcomp - $DISPLAY

This didn't work for me, but workaround from 6th comment did.

> I think you can get some useful information from [here](https://bugs.freedesktop.org/show_bug.cgi?id=50611)

I commented
```
group 2 = AltGr;
group 3 = AltGr;
group 4 = AltGr;
