### ISSUE TITLE
Sometimes I lose control

### ISSUE THREAD

**Issue by Trevoke** [stumpwm/stumpwm#187] opened 2015-02-19 23:32 UTC
Sometimes, I'm not sure what I do, but I end up unable to call out to StumpWM.

Just now, I started emacs and tried a Ctrl+Click, and now I can't send commands to either emacs or stumpwm (as far as I can tell).

Thankfully, through clicking, I was able to enable to find emacs' menu and quit emacs that way, which restored responsiveness for stumpwm.

How do I recover from such a situation?

**Comment by dbjergaard** [comment] 2015-02-20 01:23
I chuckled at the title of this issue, but to help I'll need more info.
Can you give specific instructions to reproduce with an empty init file?
That will rule out a lot of potential sources.

Also, is this just with emacs or does it appear in other programs? Does
it happen when there are multiple frames or heads, or does it happen
when emacs is the only focused window on a screen? Do you have the mouse
focus policy set to sloppy? 

Cheers,

    Dave

**Comment by Trevoke** [comment] 2015-02-20 01:33
I'll do my best to try to reproduce it.

I have not configured StumpWM at all - I've just started my way through the manual and I'm up to the introduction to frames.
This happened on a laptop, not connected to anything. I think, both times, there were two frames split horizontally (as in they were side by side, not one on top of the other).

It happened most recently with emacs, and emacs was the left frame.

I don't know how to set the mouse focus policy, so I'd guess .. Whatever the default is.

I'm excited to use StumpWM since it'll give me a chance to dive into Common Lisp (my lisp usage has been limited to emacs-lisp so far), so I'm eager to help as much as I can. Nothing like a complete beginner to root out crazy edge cases..

**Comment by dbjergaard** [comment] 2015-02-20 01:42
Hmm, to be clear: When you have emacs in a frame and you press C-t (the
default prefix key), the cursor doesn't change shapes? C-t C-g should be
enough to change the cursor and change it back.  

If your talking about emacs focus, its possible that somehow emacs is
being raised in a frame that isn't focused and since it doesn't have
focus you won't be able to interact with emacs. Then when you clicked on
emacs, the frame was refocused and you could quit emacs.  I'm shooting
in the dark here though.

Just remember: by default you have to select the frames yourself.  If
you set the mouse policy to sloppy, the focus will follow your mouse
which may feel more familiar until you integrate with stumpwm's ideas
for handling focus.

Cheers,

    Dave

**Comment by Trevoke** [comment] 2015-02-20 16:16
When I'm in emacs, normally, I can do `C-t C-g` and see the cursor change and change back.

What usually happens is that I start emacs, I start using it normally, then _something_ happens (most likely I press some keychord) and emacs loses focus, but no other frame seems to gain focus, and StumpWM seems to not have focus.

Is there a chance that I inadvertently start some keychord combination with StumpWM and I just don't know how to get out of it -- or maybe my escape keychords gets eaten by some feature of StumpWM and I don't know how to fix that?)

**Comment by dbjergaard** [comment] 2015-02-20 17:35
Any of the stumpwm keys that take input would do what you describe.
Those are:
C-t ;
C-t :
C-t a
C-t h
C-t r (especially confusing because you have to hit RET to get out)

    Dave

**Comment by Trevoke** [comment] 2015-02-20 23:08
Okay.

I reproduced the behavior.

I had emacs on the left frame and Google Chrome on the right frame (focused on a textbox). The focus was on the Chrome frame. I did a Ctrl+Click on emacs, which triggered the mouse menu. I chose the buffer menu and switched to another buffer...

And lost control.

**Comment by dbjergaard** [comment] 2015-02-24 16:34
I can't reproduce this (using firefox).  Can you do the following:
(back up .xinitrc and .xsession first)
```
echo "exec stumpwm" >> ~/.xinitrc
rm ~/.xsession; ln -s ~/.xinirtc ~/.xsession
mv ~/.stumpwmrc{,.bak}
```
Then launch stumpwm (either with startx, or using your display manager, choose Xsession)
From stumpwm, launch emacs (C-t ! emacs RET), split the frame and open chrome with C-t ! google-chrome (or whatever the name of the binary is).

If the issue is still there, we can dig in, if not, it is something in the way you're launching stumpwm, or in your .stumpwmrc

I'm still not sure if this is a stumpwm issue, or if it has something to do with the new tiling paradigm.  If its the latter we definitely need better documentation!

**Comment by kgunders** [comment] 2015-02-25 21:47
This happens in multiple apps, not just emacs, e.g. Roxterm.  Basically loose keyboard i/o. Try clicking about a bit and eventually you will be restored.  If you're unlucky, end up Ctl-Alt-FX to another term to pkill stumpwm.  There has been some discussion of this on #stumpwm.  scottj also sees this behavior sometimes.

**Comment by dbjergaard** [comment] 2015-03-09 16:59
Can someone post a comprehensive way to reproduce this issue? Also include which linux distro and lisp flavor/version your using. Minimally I would need:
1. How to set up stumpwm (ie "exec stumpwm"  in .xinitrc
2. How to start stumpwm (startx from a linux tty, or from a login manager like lightdm)
3. Specific steps to consistently make stumpwm lose control (ie split the frame, open emacs, click the empty frame) 

Thanks

**Comment by dbjergaard** [comment] 2015-03-27 00:10
I may have just experienced this. Can you confirm if switching focus to another frame and switching back give you control? In my case it did.

**Comment by dbjergaard** [comment] 2015-06-09 13:40
I'm going to mark this as duplicate of #196 for now, if someone can prove otherwise I'll treat them as separate issues.  This is a really annoying bug.

**Comment by scottjad** [comment] 2015-06-09 17:27
My having this bug was mentioned above. I was never quite sure if this bug was the one I have experienced for a long time (though admittedly I haven't upgraded to 0.9.9). If it is, then it is not a duplicate of #196, because the following is not true:

"Observed: the window doesn't have focus and clicking it doesn't give it focus. The only way to focus the window is to cycle through the frames again."

In the bug I see, that I would describe as losing control, it is impossible to cycle through the frames with stumpwm keybindings because stumpwm doesn't respond to keystrokes until a window is focused, which can be done by clicking on the window (or using a window switching app outside of stumpwm).

Again, I'm not sure my bug is the same as the OP, because I've only experienced it when the current window closes (and a new window fails to get focus for some reason).

**Comment by dbjergaard** [comment] 2015-06-09 17:55
Ok, I will consider this.  I suspect that the two issues are intertwined at some
level.  If I fix the other bug and this isn't fixed, then I'll remove the
duplicate tag.  I'm affected by the other bug all time time so I think I have a
better shot at fixing it than this one since I don't have a bullet proof way to
reproduce this one.

    Dave

**Comment by kgunders** [comment] 2015-09-13 05:52
Apologies, as my github acct. had an old, invalid email address so I missed this.   

I saw this on 0.9.9.  I am presently on master, but I've not pulled since June.  I continue to see this behavior.  

1) I am on Archlinux, updated often.
2) I use lxdm.  
3) Lisp flavor is SBCL.  
4) I am using an external USB keyboard and mouse connected via wires (i.e. not a laptop, no wireless bluetooth, etc.).  The mainboard sports USB2.  
5) I almost always have at least one instantiation of Emacs, Firefox, and Roxterm open somewhere, and typically more.  
6) I often use >1 group.  

As far as I can discern, this is an intermittent issue, and I am unable to reproduce it w/any kind of consistency.  

Sorry, but that's the best I've got on this.

**Comment by dbjergaard** [comment] 2016-01-21 16:09
Was this ever resolved? Its a duplicate, and the other bug was fixed, but if this behavior is still there, please let me know, otherwise I'll close this one too.

**Comment by Trevoke** [comment] 2016-01-21 16:18
If the other bug was fixed, close this one too. I've unfortunately stopped
using StumpWM for the moment, though I look forward to being able to get
back to it.

Thanks for all your work on this!

**Comment by dbjergaard** [comment] 2016-01-21 16:26
If anyone else in the thread is affected, please reopen

**Closed by dbjergaard** 2016-01-21 16:26 UTC
Labels: duplicate
