### ISSUE TITLE
Error in command 'redisplay': No applicable method for generic function WM-SIZE-HINTS-WIDTH-INC

### ISSUE THREAD

**Issue by elektito** [stumpwm/stumpwm#775] opened 2020-04-26 20:48 UTC
The only way I've been able to produce this error is install python arcade library (`pip install arcade==2.3.15`) and run the following python script:

    import arcade
    arcade.Window(800, 600, 'Foo', resizable=True)
    arcade.run()

With that window open and active, executing the "redisplay" command would result in the following error:

    Error In Command 'redisplay': There is no applicable method for the generic function
                                               #<STANDARD-GENERIC-FUNCTION XLIB:WM-SIZE-HINTS-WIDTH-INC (1)>
                                             when called with arguments
                                               (NIL).

This is in Ubuntu 18.04 with Python 3.7.5. StumpWM is at the latest master version as of now, and the `version` command reports: `19.11-140-g7f43263`.

**Comment by erenhatirnaz** [comment] 2020-10-06 09:57
Same here.

Open random image with `feh` and execute `redisplay` produces this error message:
```text
Error In Command 'redisplay': The value
                                           NIL
                                         is not of type
                                           XLIB:WM-SIZE-HINTS
```
Also `feh` repeats the image file because I guess it doesn't know corrently width and height of the window. To reproduce this issue:
* Open random file with `feh`. It repeats the image both vertically and horizontally. 
* Split the screen horizontally or vertically (`vsplit` / `hsplit`)
* Return back to single window (`only`).
* Now `feh` shows image without repeats.

Screenshot feh repeating issue:
![ksnip_20201006-124307](https://user-images.githubusercontent.com/5196786/95186235-73aa4f80-07d2-11eb-872b-88c6c449189c.png)

My StumpWM version is = `19.11 Compiled On Tue Sep 29 2020 18:39:46`

Related issue from another window manager: https://github.com/swaywm/sway/issues/3106

**Comment by PuercoPop** [comment] 2020-10-06 14:50
@elektito This should fix the error you are encountering https://github.com/stumpwm/stumpwm/pull/819. Could you check if you encounter the same error when running from that branch?

@erenhatirnaz The bug you report although similar is different. In the OP the issue is running into a missing method specialization for NIL in the generic function. In your case it is type error. I'm going to extract it to a separate issue so we don't lose track of it.

**Comment by elektito** [comment] 2020-10-06 21:39
Looks like for some reason stumpwm crashes upon startup with this branch. I'm just sent back to lightdm login screen after a second. Not sure how to see what is causing the crash.

**Comment by PuercoPop** [comment] 2020-10-07 01:11
@elektito Does only that branch crash or does the current master branch does as well? If so I think it may be related to the new logging to a file functionality I implemented :grimacing:

**Comment by elektito** [comment] 2020-10-07 07:09
No, I'm actually a few commits behind so it could be that. But I'm working from home on this PC right now, so better not mess around. I'll try that after working hours.

Also, there is a new logging facility? Are there any docs you can point me to?

**Comment by PuercoPop** [comment] 2020-10-07 16:15
There are no new docs, it just that we persist logs to a file by default now. You still have to change the *debug-level* to a number higher than 0.

**Comment by elektito** [comment] 2020-10-07 21:14
I cannot even build anything after commit 4f7b643. I get errors like:

    make: *** No rule to make target 'xdg-base-dirs.lisp', needed by 'stumpwm'.  Stop.

**Comment by elektito** [comment] 2020-10-07 21:26
Okay. I messed up. I _am_ able to build master, the error was for one I was trying to bisect. Anyways, stumpwm doesn't start for me with the very latest master as of now (5a3669).

**Comment by femnad** [comment] 2020-10-07 21:59
I think the issue with 5a3669f is that the data directory (`$HOME/.stumpwm.d`) is missing the executable bit so the log file isn't being able to be created in it. As a workaround you can create that directory yourself or add the executable bit after after Stumpwm fails to start for the first time.

Created #821 to change the initial permissions.

**Comment by elektito** [comment] 2020-10-07 22:05
That was indeed the problem. After giving the .stumpwm.d directory the executable permission, stumpwm starts up properly. I also could test the above-mentioned PR 819 and can confirm that it fixes the original issue.

**Comment by PuercoPop** [comment] 2020-10-08 13:29
> can confirm that it fixes the original issue.

Thanks, closing then

**Closed** 2020-10-08 13:29 UTC
