### ISSUE TITLE
StumpWM freezing since 1c5fdcf

### ISSUE THREAD

**Issue by ghferrari** [stumpwm/stumpwm#246] opened 2016-03-27 17:16 UTC
Hi all,

StumpWM no longer works for me since https://github.com/stumpwm/stumpwm/commit/1c5fdcf439b6769e53144c61dfbbfe05029183f2

As soon as I login, the screen freezes and the keyboard is unresponsive. I've tried connecting to the running lisp instance via swank and using (copy-unhandled-error) but this doesn't report anything.

The last line I see in my debug file is a map-request.

I might be able to investigate further if someone could instruct me what to do.

Thanks for your help,

Geoff

**Comment by dbjergaard** [comment] 2016-03-28 00:34
Hi,

Can you double check the link? I can't see what commit it was.

**Comment by PuercoPop** [comment] 2016-03-28 01:31
@dbjergaard The commit they are referring to is https://github.com/stumpwm/stumpwm/commit/1c5fdcf439b6769e53144c61dfbbfe05029183f2

> Replace the fullscreen-SDL skip-raise heuristic with grabbing the server

**Comment by dbjergaard** [comment] 2016-05-13 21:43
@ghferrari can you confirm this bug wit ha minimimal .stumpwmrc and launch stumpwm using "exec /path/to/stumpwm" in your .xinitrc.  Sometimes programs will interact adversely with stumpwm and narrowing down the culprit will help us isolate the bug.

**Comment by ghferrari** [comment] 2016-07-09 14:51
Hi David,

Sorry for the slow response. I've finally found time to look at this further. I'm using stumpwm built today from commit 7d5b5eb76 on up to date debian stretch with clx etc provided by quicklisp.

I can now reproduce the hanging behaviour consistently. I'm using a minimal xinitrc as you advised above, and with the following in my .stumpwmrc:

```
(in-package :stumpwm)

(setq *default-package* :stumpwm)

(stumpwm:toggle-mode-line (stumpwm:current-screen)
                          (stumpwm:current-head))

(setf *screen-mode-line-format*
			(list
			 '(:eval (run-shell-command "amixer get Master" t))))

(stumpwm:run-commands "exec xterm")

```

The problem does seem specific to running the amixer command for my `*screen-mode-line-format*`, but the command executes without an error and I can't see why its output would cause a problem. In my minimal example it produces multi-line output, but reducing the output to single line by adding " | grep -i simple" to the shell-command produces the same problem.

Another piece of useful information. The mode-line is displayed just fine after setting the format. The hang only happens when running a new application that produces a new windows. That's when the freeze occurs.

I can investigate further if you have any advice. Otherwise I've reached the limit of my debugging skills.

Thanks, Geoff

**Comment by dbjergaard** [comment] 2016-07-09 17:01
Hi Geoff,

Thanks for the additional info! While your format line should work, something is happening that is causing that to hang, which in turn is hanging stumpwm.  My guess is that amixer exits the first time (or is not run at all) when stumpwm starts, and then as soon as you launch a window it triggers the mode-line to be refreshed which evals the amixer command and hangs stumpwm because the amixer command never exits.  

You could try "amixer get Master &" to background amixer, or remove the 't predicate in order to have it run asynchronously.  This might cause unexpected/undefined behavior for the modeline formatter though since it expects to get a string return value tha it can further parse.  

Have you looked into the audio modules, they may solve this problem some other way already...

**Comment by dbjergaard** [comment] 2016-11-07 14:34
I'm going to close this, feel free to re-open if the issue is unresolved.

**Closed by dbjergaard** 2016-11-07 14:34 UTC

**Comment by agarick** [comment] 2017-09-09 19:32
Hi,

I encountered this same issue. I recently started using stumpwm and lisp, and noticed that certain external shell calls cause the entire wm to hang. After going through numerous searches and attempts, the following ended up working for me. Though I still don't understand why exactly.

```lisp
(run-prog-collect-output "/bin/sh" "-c" "some command")
```

Note, the external command (last arg) is a single string, eg. `"amixer get Master"`.

**Comment by agarick** [comment] 2017-09-12 03:06
Scratch my last comment, sorry. Those solutions are not accurate and stumpwm still freezes.

For the moment, I'm working around this by using a global var and a thread. I'd love to know if there's a simpler solution.

```lisp
(defvar *foo* "")

(defun baz ()
  (bt:make-thread
   (lambda ()
     ; or (run-shell-command "blahblah" t)
     (run-prog-collect-output "blahblah")))
  *foo*)

(defun qux ()
  (do-stuff-and-return-foo *foo*))

(setf *screen-mode-l ... etc)
```
