### ISSUE TITLE
Latest xfce4-panel breaks mode-line show/hide

### ISSUE THREAD

**Issue by voobscout** [stumpwm/stumpwm#293] opened 2016-12-04 10:02 UTC
Running xfce4 4.12.1 with stumpwm from git on arch linux.

Been running stumpwm with xfce4-panel for a few years, everything worked, i.e. when mode-line cmd was issued the xfce4-panel got hidden/shown and windows did not overlap it.

Now though, xfce4-panel is always rendered "under" windows and mode-line cmd shows/hides the stumpwm modeline and not the xfce4-panel.

The impression this gives me as a user is that xfce4-panel presence is no longer being recognized by stumpwm.

Any and all help/advice is very much appreciated, i would really like to keep using xfce4-panel with stumpwm.

**Comment by dbjergaard** [comment] 2016-12-04 17:07
We haven't changed anything that would affect the panel recently.  Can you confirm that its the latest version of the panel? Stumpwm does its best to be standard compliant, so if this recently started when the panel was updated, it sounds like xfce-panel isn't following the protocol correctly anymore.  

If it is a problem in stumpwm, then we can do something. If not, you'll have to take the issue up with the xfce maintainers.

**Comment by dbjergaard** [comment] 2017-01-23 20:37
Reply if you can show that stumpwm is at fault and I'll reopen, otherwise there isn't much we can do.

**Comment by voobscout** [comment] 2017-01-30 08:01
Tried to switch to mate-panel, same problem. It could have something to do with gtk3. One of those days i'll do a proper test and isolate this issue.

**Comment by openjohn** [comment] 2017-02-20 22:28
I believe I'm also seeing this problem.

I'm running XFCE (v4.12.1) with StumpWM (built from source) on FreeBSD 11.

Glad to provide additional details if that would be helpful.

**Comment by zcassini** [comment] 2017-02-21 15:53
I'm also having trouble with this.
I just came back to stumpwm.  I had compiled and installed it last spring.
So I got it all setup and had the xfce-panel looking good.
I did some system updates and also pulled the latest stumpwm from github and compiled it.
Now stumpwm draws over the panel.  I also tried razor-panel and it has the same problem.

**Comment by zcassini** [comment] 2017-02-21 16:05
Pulled down the 0.9.9 version from Nov 2014 and compiled and installed that.  The panels are working correctly in that release.

**Comment by dbjergaard** [comment] 2017-02-21 16:41
OK You got my attention ;)
My first step will be to diff 0.9.9 with the current head of master and look for mode-line related changes. If you want to start there be my guest.  My schedule is really busy at the moment.

**Comment by zcassini** [comment] 2017-02-21 16:58
I tracked it down to the first commit on Nov 7 92690c94dfdb0317069a33f566a5e8de8c967d8b
The previous commint on Nov1/Oct 31 92bc2c12c9b2a45f086c46dc3c74676a7cb20b91 works great.

**Comment by jorams** [comment] 2017-03-26 11:39
I'm fairly certain this was caused by #288, which did indeed reorganize the mode line quite a bit. I'll try to find out where it went wrong.

**Comment by jorams** [comment] 2017-03-26 11:58
This should be fixed by 7d631237f466e8fe103bd3398122fd9709beb026.

I tested with xfce4-panel, and it now does what I think it should be doing. Could you confirm and reopen if it is not yet fixed?

**Comment by zcassini** [comment] 2017-03-26 13:30
@jorams I pulled and tested the latest commit.
 It works on the default monitor only though.
Tested with xfce4 and razor panels.  
I don't think I can reopen the issue.
Thanks for working on this.

**Closed** 2023-09-28 01:09 UTC
