### ISSUE TITLE
Stumpwm crashes after waking from hibernate with another monitor removed

### ISSUE THREAD

**Issue by zwz** [stumpwm/stumpwm#144] opened 2014-09-15 09:28 UTC
I run stumpwm on my laptop. Sometimes I would like to use a larger monitor as an extension of the screen with the shell cmd: 
xrandr --output LVDS --auto --right-of VGA

And then I just let the system hibernate, and get rid of the larger monitor.
After waking up the system, I find stumpwm reports an unhandled error:
The index 1 is too large

As far as I know, tt has something to do with the frame.

**Comment by dbjergaard** [comment] 2015-04-10 13:24
Not quite fixed, still looking into a solution.

**Comment by dbjergaard** [comment] 2016-01-25 00:34
@zwz If you run refresh-heads right after you wake the computer, does stumpwm still crash? I expect that the issue is that the heads are getting out of alignment with what is physically available to X11.  refresh-heads forces stumpwm to reexamine which monitors are available.

**Comment by dbjergaard** [comment] 2017-01-19 21:57
Can someone who can reproduce this bug see if the latest commit fixes it?

**Comment by dmb2** [comment] 2019-11-26 22:14
I think I've addressed this issue in the latest commit.  I'm closing this for now.

**Closed by dmb2** 2019-11-26 22:14 UTC
