### ISSUE TITLE
Crash on opening Steam.

### ISSUE THREAD

**Issue by elektito** [stumpwm/stumpwm#528] opened 2018-11-25 02:02 UTC
The latest commit on master causes StumpWM to crash as soon as Steam is opened. This is the backtrace I get:

```
The value
  NIL
is not of type
  VECTOR
when binding #:LOOP-ACROSS-VECTOR-0
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005BB8103}>
0: (STUMPWM::ESCAPE-CARET NIL)
1: (STUMPWM::XWIN-TO-WINDOW #<XLIB:WINDOW :0 600021>)
2: (STUMPWM::PROCESS-MAPPED-WINDOW #S<screen #<XLIB:SCREEN :0.0 1920x1080x24 TRUE-COLOR>> #<XLIB:WINDOW :0 600021>)
3: ((LAMBDA (&REST #:G0 &KEY :PARENT :SEND-EVENT-P :WINDOW &ALLOW-OTHER-KEYS) :IN "/home/mostafa/source/stumpwm/events.lisp") :PARENT #<XLIB:WINDOW :0 29E> :SEND-EVENT-P NIL :WINDOW #<XLIB:WINDOW :0 600021>)
4: (STUMPWM::HANDLE-EVENT :DISPLAY #<XLIB:DISPLAY :0 (The X.Org Foundation R11906000)> :EVENT-KEY :MAP-REQUEST :EVENT-CODE 20 :SEND-EVENT-P NIL :SEQUENCE 329 :PARENT #<XLIB:WINDOW :0 29E> :EVENT-WINDOW #<XLIB:WINDOW :0 29E> :WINDOW #<XLIB:WINDOW :0 600021>)
5: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT))
6: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
7: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT) {7FFFF674F03B}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1005BB8103}>> T NIL)
8: ((FLET SB-IMPL::TIMEOUT-BODY :IN XLIB:PROCESS-EVENT))
9: (XLIB:PROCESS-EVENT #<XLIB:DISPLAY :0 (The X.Org Foundation R11906000)> :HANDLER #<FUNCTION STUMPWM::HANDLE-EVENT> :TIMEOUT 0 :PEEK-P NIL :DISCARD-P NIL :FORCE-OUTPUT-P T)
10: ((FLET "WITHOUT-INTERRUPTS-BODY-29" :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
11: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN STUMPWM::DISPATCH-ALL) {7FFFF674F4AB}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1005BB8103}>> T NIL)
12: ((FLET STUMPWM::DISPATCH-ALL :IN "/home/mostafa/source/stumpwm/stumpwm.lisp") #<XLIB:DISPLAY :0 (The X.Org Foundation R11906000)>)
13: ((:METHOD IO-LOOP (STUMPWM::SBCL-IO-LOOP)) #<STUMPWM::SBCL-IO-LOOP {1004142303}> :DESCRIPTION "StumpWM") [fast-method]
14: (STUMPWM::STUMPWM-INTERNAL-LOOP)
15: (STUMPWM::STUMPWM-INTERNAL ":0")
16: (STUMPWM ":0")
17: ((LAMBDA NIL :IN "/home/mostafa/source/stumpwm/make-image.lisp"))
18: ((FLET SB-UNIX::BODY :IN SB-EXT:SAVE-LISP-AND-DIE))
19: ((FLET "WITHOUT-INTERRUPTS-BODY-36" :IN SB-EXT:SAVE-LISP-AND-DIE))
20: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))
```

I suspected this might have something to do with Steam's title bar being empty, but I couldn't reproduce the problem with any other window with an empty title.

Reverting the last commit (c341605af) fixes the issue.

**Comment by PuercoPop** [comment] 2018-11-25 02:17
This is a dupe of #524, lets move the discussion there. Could you try the fix described in https://github.com/stumpwm/stumpwm/issues/524#issuecomment-441230062

**Closed by PuercoPop** 2018-11-25 02:17 UTC
