### ISSUE TITLE
Odd interaction with some drop-down menu elements in Chromium-based web browsers

### ISSUE THREAD

**Issue by 2kays** [stumpwm/stumpwm#894] opened 2021-06-06 21:29 UTC
(For the record #527 looks really similar to this issue, but I'm not 100% comfortable ascribing this problem to the same GH issue...)

---

Steps to reproduce:
1. Run a Chromium-based web browser in stumpwm (Chromium, Chrome, Vivaldi)
2. Visit any of the following sites: www.aliexpress.com www.teksavvy.com www.trackitt.com (I'm sure there are 1000s more)
3. Attempt to interact with the drop-down navigational menus on the websites
4. Observe that clicking menu items results in the menu disappearing without following the link.
  The menu disappears seemingly before the click goes through -- often meaning something _behind_ the link gets clicked instead.

---

Stumpwm version: `master`, SBCL `"2.1.1"`, `xlib:*version* ;=> "MIT R5.02"`

I tested this issue across:
* Multiple Machines
* Input Methods (Mouse, TrackPoint)
* Linux distros (Arch, Ubuntu)
* Browsers (Vivaldi, Chrome), incognito modes included
* Environments (Gnome, i3, and even CLFSWM to see if it was a CLX issue -- it wasn't)

The only environment triggering this behaviour is stumpwm (with no config).

It's not a regression either -- I recompiled stumpwm from releases in 2014 and 2017 and it had exactly the same issue.

---

_Possibly unrelated, but these menus also disappear when I hover them, and then press the prefix key `C-t`..._

**Comment by DerGuteMoritz** [comment] 2021-09-08 11:51
I experience the exact same issue. During research I came across https://www.reddit.com/r/archlinux/comments/mqgyg5/problem_with_chromium_and_css_dropdown_hover_menus/ which sounds pretty much like the same issue but caused by fluxbox WM in that case. The post goes on to suggest `--enable-features=UseOzonePlatform` as a workaround but unfortunately, that doesn't seem to fix it for stumpwm.

**Comment by DerGuteMoritz** [comment] 2021-09-08 12:03
Moments later I found https://bugs.chromium.org/p/chromium/issues/detail?id=713746 which suggests passing `--disable-features=SendMouseLeaveEvents` as a workaround. So far it looks like this indeed also does the trick for stumpwm :crossed_fingers: Not sure what exactly the consequences are of this flag, though.

**Comment by 2kays** [comment] 2021-09-08 12:30
That fixed it for me too :tada:. Obviously there's a weird Chrome interaction with some WMs, then. I'll trial this workaround and report back any unexpected behaviours.

**Comment by nspaeth** [comment] 2021-12-27 05:10
I've had this problem for a while and gave up on it after reporting it at bugs.chromium.org. 

Is this chromium bug, or a window manager bug? If it is WM bug, then I'd think that the issue should remain open until a workaround isn't necessary.
If it is a chromium bug, then I found it very difficult to find a solution for except for only serendipitously stumbling on this issue here, and therefore it might be good to add some documentation some stumpwm documentation about it given how widely used chromium is.

**Comment by nspaeth** [comment] 2022-01-10 20:16
@dmb2 According to the feedback on the [chromium bug tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=1192979#c15), this is an issue that must be fixed in stumpwm, so I believe this issue should be re-opened.

**Comment by aykaramba** [comment] 2022-06-19 04:01
Huh, never noticed this before.  Issue confirmed.

**Comment by jorams** [comment] 2022-08-06 20:40
After a few hours of investigation and testing I've just opened #1017, which fixes this. I'm not convinced this isn't a bug in Chromium, but the new behavior matches most other window managers and no longer triggers the problem.

**Comment by aykaramba** [comment] 2022-08-07 08:23
That is incredibly interesting.  Thank you very kindly for tracking this down.

**Closed** 2022-08-09 20:51 UTC
