### ISSUE TITLE
Build failure (The function COMMON-LISP:NIL is undefined)

### ISSUE THREAD

**Issue by Jehops** [stumpwm/stumpwm#541] opened 2018-12-17 03:53 UTC
It seems strange given the contents of the commit, but the issue seems to have been introduced in 9f0c913.

Build failure with 9f0c913: http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2018-12-16_23h21m42s/logs/errors/stumpwm-18.11.1.log

Successful build with f5113ad: http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2018-12-16_23h18m47s/logs/errors/stumpwm-18.11.1.log (Please ignore the plist error at the end, those are related to the FreeBSD package).

**Comment by Jehops** [comment] 2018-12-17 13:34
Hi @PuercoPop,

I'm not certain, but have no indication that it's related to `expose`.  Here are the last bits of the build (current HEAD).

```
....
; wrote /wrkdirs/usr/ports/x11-wm/stumpwm/work/stumpwm-18.11-1-ga13db62/remap-keys-tmp267Y2N80.fasl
; compilation finished in 0:00:00.010
; compiling file "/wrkdirs/usr/ports/x11-wm/stumpwm/work/stumpwm-18.11-1-ga13db62/version.lisp" (written 16 DEC 2018 11:46:15 PM):
; compiling (IN-PACKAGE :STUMPWM)
; compiling (EXPORT (QUOTE #))
; compiling (DEFPARAMETER *VERSION* ...)
; compiling (DEFCOMMAND VERSION ...)

; wrote /wrkdirs/usr/ports/x11-wm/stumpwm/work/stumpwm-18.11-1-ga13db62/version-tmpOUPE5FSJ.fasl
; compilation finished in 0:00:00.002
;
; compilation unit finished
;   caught 1 STYLE-WARNING condition

debugger invoked on a UNDEFINED-FUNCTION in thread
#<THREAD "main thread" RUNNING {10005205B3}>:
  The function COMMON-LISP:NIL is undefined.

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE ] Retry using NIL.
  1: [USE-VALUE] Use specified function
  2:             Ignore runtime option --eval "(stumpwm::generate-manual)".
  3: [ABORT    ] Skip rest of --eval and --load options.
  4:             Skip to toplevel READ/EVAL/PRINT loop.
  5: [EXIT     ] Exit SBCL (calling #'EXIT, killing the process).

(SB-IMPL::RETRY-%COERCE-NAME-TO-FUN NIL NIL)
0]
```
To test, I patched stumpwm.texi.in to revert @dbjergaard's changes in 9f0c913 and applied them to HEAD and the build finished successfully.  I also tried without the patch, but with the current HEAD of clx, but the build still fails.

**Comment by PuercoPop** [comment] 2018-12-18 02:40
I'm not familiar with FreeBSD, but I've managed to build/compile StumpWM on OpenBSD w/o any hiccups. What exactly is the 'recipe' of the FreeBSD 'port' of StumpWM?

**Comment by Jehops** [comment] 2018-12-19 01:16
I found some time to dig a little deeper.

1. A [manual build](https://ftfl.ca/blog/2015-01-27-stumpwm-freebsd.html) fails with the same error.
2. The build of StumpWM itself finishes successfully.  It's building the documentation, which is part of the `all` make target, that fails.  This makes sense given the commit that introduced the problem.

You can see the FreeBSD port recipe [here](https://svnweb.freebsd.org/ports/head/x11-wm/stumpwm/Makefile?revision=486775&view=markup).

**Comment by PuercoPop** [comment] 2018-12-19 02:57
Ah that makes more sense, basically we are trying to get the function of a non-existent function. I can reproduce now with the following. I should send a PR shortly

```
(with-open-file (in #P"stumpwm.texi.in")
  (loop :for line := (read-line in nil)
        :while line
        :when (uiop:string-prefix-p "@@@ " line)
          :collect (symbol-function (find-symbol (string-upcase (subseq line 4)) :stumpwm))))
```

**Comment by PuercoPop** [comment] 2018-12-19 03:10
Having some trouble pin pointing the symbol. Going to look into it over the weekend, but I should have all the necessary info. Thanks for reporting the issue

**Comment by Jehops** [comment] 2018-12-19 12:50
Hi @PuercoPop.  I went one step further and just submitted the PR.  Thanks for your help tracking this down.

**Comment by PuercoPop** [comment] 2018-12-19 13:36
Thanks to you, it is important to support BSDs given that if you track the reason for the wrapper in the first place it is another example of how Linux :fire:

https://bugzilla.kernel.org/show_bug.cgi?id=11014#c2 

I've merged the PR, although maybe we should provide a non-linux implementation that just calls `read-line`?

**Closed by PuercoPop** 2018-12-19 13:36 UTC
