### ISSUE TITLE
Listing exec completions is too slow

### ISSUE THREAD

**Issue by brandoninvergo** [stumpwm/stumpwm#747] opened 2020-03-09 12:09 UTC
I'm not sure exactly when the feature was added, but now when running the `exec` command, when typing an executable's name a big list of possible matches pops up, narrowing down as you type more.  The problem is that the initial generation of this list is too slow and while it is loading, the next keypress is ignored.

So, as an example, I'll run `exec` and start typing "firefox". After typing "f", it loads a big list of all executables that start with "f". Meanwhile, I'm continuing typing in "irefox". That "i" is missed, though, so by the time I'm done typing, the prompt says "frefox". Incidentally, if focus is on a window with text input, the "i" is actually entered in that window's text box instead of in StumpWM's input box.

**Comment by equwal** [comment] 2020-03-09 23:03
It is straightforward to replace this with historical completion only from this session.

**Comment by equwal** [comment] 2020-03-09 23:48
Also, I think this is a duplicate of #741.

**Comment by brandoninvergo** [comment] 2020-03-10 09:58
Ah very sorry, I somehow completely missed #741 (I swear, I did check before sending the bug report). Apologies for the noise.

**Comment by PuercoPop** [comment] 2020-03-10 17:21
A well written bug report is not noise, even if it was a duplicate. Thanks for taking the time to submit it. Closing in favor of 741

**Closed by PuercoPop** 2020-03-10 17:21 UTC
