### ISSUE TITLE
Caught 'Unable to encode character 8217 as :ASCII.' at the top level. Please report this.

### ISSUE THREAD

**Issue by clijunky** [stumpwm/stumpwm#448] opened 2018-02-28 15:29 UTC
Looks like there is a problem with the title of a web browser.

I got this error when running $ stumpish windows

Full error below:

```
;                                                                                                                                                              
; caught WARNING:                                                                                                                                              
;   undefined variable: *BROWSER*                                                                                                                              
;                                                                                                                                                              
; compilation unit finished                                                                                                                                    
;   Undefined variable:                                                                                                                                        
;     *BROWSER*                                                                                                                                                
;   caught 1 WARNING condition                                                                                                                                 
Caught 'Unable to encode character 8217 as :ASCII.' at the top level. Please report this.                                                                      
Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1005254C63}>                                                                                          
0: ((LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX))                                                                                                   
1: (SB-IMPL::CALL-WITH-SANE-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10083E2F7B}>)                                         
2: (SB-IMPL::%WITH-STANDARD-IO-SYNTAX #<CLOSURE (LAMBDA NIL :IN SB-DEBUG::FUNCALL-WITH-DEBUG-IO-SYNTAX) {10083E2F4B}>)                                         
3: (SB-DEBUG:PRINT-BACKTRACE :STREAM #<SB-IMPL::STRING-OUTPUT-STREAM {10083E2EA3}> :START 0 :FROM :DEBUGGER-FRAME :COUNT 100 :PRINT-THREAD T :PRINT-FRAME-SOURCE NIL :METHOD-FRAME-STYLE NIL)                                                                                                                                 
4: (STUMPWM::BACKTRACE-STRING)                                                                                                                                 
5: ((:METHOD STUMPWM::HANDLE-TOP-LEVEL-CONDITION (SERIOUS-CONDITION)) #<SB-IMPL::OCTETS-ENCODING-ERROR {10083E2D53}>) [fast-method]                            
6: (SIGNAL #<SB-IMPL::OCTETS-ENCODING-ERROR {10083E2D53}>)                                                                                                     
7: (ERROR #<SB-IMPL::OCTETS-ENCODING-ERROR {10083E2D53}>)                                                                                                      
8: (SB-IMPL::ENCODING-ERROR :ASCII " 1+Dick?s Sporting Goods Stops Selling Assault-Style                                                                       
 2*(stumpwm)user@localhost: ~                                                                                                                                  
" 7)                                                                                                                                                           
9: (SB-IMPL::STRING->ASCII #<unavailable argument> #<unavailable argument> #<unavailable argument> #<unavailable argument>)                                    
10: (STUMPWM::HANDLE-STUMPWM-COMMANDS #<XLIB:WINDOW :1 143>)                                                                                                   
11: (STUMPWM::HANDLE-EVENT :DISPLAY #<XLIB:DISPLAY :1 (The X.Org Foundation R11804000)> :EVENT-KEY :PROPERTY-NOTIFY :EVENT-CODE 28 :SEND-EVENT-P NIL :SEQUENCE 5582 :WINDOW #<XLIB:WINDOW :1 143> :EVENT-WINDOW #<XLIB:WINDOW :1 143> :ATOM :STUMPWM_COMMAND :TIME 331267334 :STATE :NEW-VALUE)                               
12: ((FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT))                                                                                       
13: ((FLET #:WITHOUT-INTERRUPTS-BODY-387 :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))                                                                             
14: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN XLIB:PROCESS-EVENT) {7FFFF2E7701B}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1005254C63}>> T NIL)                                                                                
15: ((FLET SB-IMPL::TIMEOUT-BODY :IN XLIB:PROCESS-EVENT))                                                                                                      
16: (XLIB:PROCESS-EVENT #<XLIB:DISPLAY :1 (The X.Org Foundation R11804000)> :HANDLER #<FUNCTION STUMPWM::HANDLE-EVENT> :TIMEOUT 0 :PEEK-P NIL :DISCARD-P NIL :FORCE-OUTPUT-P T)                                                                                                                                               
17: ((FLET #:WITHOUT-INTERRUPTS-BODY-387 :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))                                                                             
18: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN STUMPWM::DISPATCH-ALL) {7FFFF2E7750B}> #<SB-THREAD:MUTEX "CLX Event Lock" owner: #<SB-THREAD:THREAD "main thread" RUNNING {1005254C63}>> T NIL)                                                                             
19: ((FLET STUMPWM::DISPATCH-ALL :IN "/home/user/stumpwm/stumpwm.lisp") #<XLIB:DISPLAY :1 (The X.Org Foundation R11804000)>)                                   
20: ((:METHOD IO-LOOP (STUMPWM::SBCL-IO-LOOP)) #<STUMPWM::SBCL-IO-LOOP {100824FC33}> :DESCRIPTION "StumpWM") [fast-method]                                     
21: (STUMPWM::STUMPWM-INTERNAL-LOOP)                                                                                                                           
22: (STUMPWM::STUMPWM-INTERNAL ":1")                                                                                                                           
23: (STUMPWM ":1")                                                                                                                                             
24: ((LAMBDA NIL :IN "/home/user/stumpwm/make-image.lisp"))                                                                                                    
25: ((FLET #:WITHOUT-INTERRUPTS-BODY-82 :IN SB-EXT:SAVE-LISP-AND-DIE))                                                                                         
26: ((LABELS SB-IMPL::RESTART-LISP :IN SB-EXT:SAVE-LISP-AND-DIE))
```

**Comment by PuercoPop** [comment] 2018-03-06 02:41
It appears the problem is that the default-external-format of your SBCL is not `:utf-8`, but rather `:ascii` Could you paste the result of evaluating `(sb-impl::default-external-format)`?

**Comment by dmb2** [comment] 2019-11-27 23:16
Hi since the default-external-format seems to be utf-8 on most systems I'm going to close this.  It doesn't seem to be something we can fix, other than having you make specific changes to your sbcl instance.

**Closed by dmb2** 2019-11-27 23:16 UTC
