### ISSUE TITLE
Problems with one monitor above the other

### ISSUE THREAD

**Issue by cnoceda** [stumpwm/stumpwm#1099] opened 2023-05-23 10:35 UTC
iHi everyone,
I was working with two monitors and I have no problem with the monitor side-by-side it works perfect!.
I tried to configure my laptop in a configuration above and it does not work.

I try multiple configurations but one monitor above the other is not work. The thing is that when I execute `(refresh-heads)` the mode-line is located in the rigth position but the screen of the above monitor is always at 0x0 position, and overlaps with the other, but the mode-line is in the above monitor ¿?

I try a lot of configurations, but doesn't work. 

This is the xrand command:
`xrandr --output eDP1 --primary --auto --pos 0x1620 --output HDMI1 --scale 1.5x1.5 --mode 1920x1080 --pos 0x0`

In the images you can see the problem when I move the focus between the heads. 
![2023-05-23-122832_2880x3420_scrot](https://github.com/stumpwm/stumpwm/assets/58024863/d94ddb28-9b3b-4de4-b1ff-c06eb84fdc43)

![2023-05-23-122815_2880x3420_scrot](https://github.com/stumpwm/stumpwm/assets/58024863/61bda69b-704a-40bb-bec5-3173a5d5cb25)

this is the heading info
![2023-05-23-124045_903x217_scrot](https://github.com/stumpwm/stumpwm/assets/58024863/3582e1f8-b00f-4d16-960d-b5133bdf099a)

I dont know if its a bug or it's somethin i'm doing wrong.  Any ideas?

Thank you in advance.

**Comment by dmb2** [comment] 2023-05-26 20:10
Its probably a bug, this is a fairly non-standard layout so we probably aren't anticipating the RANDR configuration you have.

**Comment by Jehops** [comment] 2023-07-27 20:48
Sounds like this may be a duplicate of issue #1064?

**Comment by jorams** [comment] 2023-09-27 08:56
This indeed looks like a duplicate of #1064. It should be fixed in 7d3a67216114b69c42f49fc0613ac6d6d14e84ea.

**Closed by jorams** 2023-09-27 08:56 UTC
